### ISSUE TITLE
Error thrown using just foreman()

### ISSUE THREAD

**Issue by xmakina** [jshcrowthe/gulp-foreman#2]
_Gulpfile_

``` javascript
var gulp = require('gulp');
var foreman = require('gulp-foreman');
gulp.task('foreman', function () {
  foreman();
});
```

_Error_
[09:38:20] Using gulpfile C:\Code\crisis\gulpfile.js
[09:38:20] Starting 'foreman'...
Using executable "C:\Program Files (x86)\Heroku\bin\foreman.BAT" to run app
[09:38:20] Finished 'foreman' after 37 ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn foreman ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by jshcrowthe** [comment]
Updating the command passed to the `spawn` function call with the full executable path of foreman (or `nf` for that matter) should fix the issue. I will be testing with this: 889ff3df8fefc044199ed5d0a4c4b5ec16f4fa26

**Comment by xmakina** [comment]
That's worked great, thanks!
